version: '3.8'
services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: backend_user
      POSTGRES_PASSWORD: securepassword
    volumes:
      - ./database/setup.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - hashi

  backend:
    build: ./backend
    depends_on:
      - db
    ports:
      - "5000:5000"
    networks:
      - hashi

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - hashi

networks:
  hashi:
    name: hashi
    external: true
